create table songs (
    ID int,
    SongKey text,
    Name text,
    Description text,
    Uploader text,
    UploaderID int,
    SongName text,
    SongSubName text,
    Author text,
    BPM numeric(50,5),
    DownloadCount int,
    FinishedCount int,
    UpVotes int,
    DownVotes int,
    DetailURL text,
    DownloadURL text,
    CoverURL text,
    Difficulty text,
    AudioPath text,
    JSONPath text,
    SongTime numeric(50,5),
    DotNotes int,
    Events int,
    Notes int,
    CreationDate text,
    Obstacles int,
    DaysOld int,
    SongLength numeric(50,5),
    DifficultyRating numeric(50,5),
    PopularityRating numeric(50,5),
    PopularityRatingOverTime numeric(50,5),
    CompletionRatio numeric(50,5),
    primary key (ID, Difficulty)
);